version: '3.7'

services:
  api:
    container_name: dashboard_api
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - dashboard_network
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:12.2
    networks:
      - dashboard_network
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - dashboard_pg_data:/var/lib/postgresql/data

networks:
  dashboard_network:

volumes:
  dashboard_pg_data:
